# Generated by Django 4.2.3 on 2023-07-19 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='terms_and_conditions',
            field=models.BooleanField(default=False),
        ),
    ]
