# Generated by Django 4.2.3 on 2023-07-19 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_terms_and_conditions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='terms_and_conditions',
        ),
    ]
