# Generated by Django 4.2.3 on 2023-07-21 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0007_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimate_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_payout', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pending_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('interest_earn', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_earning', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('referral_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('lifetime_bonus', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile')),
            ],
        ),
    ]
