# Generated by Django 4.2.3 on 2023-07-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='selected_plan',
            field=models.CharField(choices=[('Basic', 'Basic Plan'), ('Standard', 'Standard Plan'), ('Silver', 'Silver Plan'), ('Premium', 'Premium Plan'), ('Gold', 'Gold Plan'), ('Diamond', 'Diamond Plan')], default='Basic', max_length=20),
        ),
    ]
