# Generated by Django 4.2.3 on 2023-07-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_account_is_active_account_selected_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_deposit_active',
            field=models.BooleanField(default=False),
        ),
    ]
