# Generated by Django 4.2.3 on 2023-08-01 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_userprofile_referral_code_userprofile_referrer'),
        ('dashboard', '0004_remove_account_is_deposit_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='account',
            name='transaction_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100)),
                ('selected_plan', models.CharField(choices=[('Basic', 'Basic Plan'), ('Standard', 'Standard Plan'), ('Silver', 'Silver Plan'), ('Premium', 'Premium Plan'), ('Gold', 'Gold Plan'), ('Diamond', 'Diamond Plan')], max_length=20)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=20)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile')),
            ],
        ),
    ]
