# Generated by Django 4.2.3 on 2023-08-01 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_userprofile_referral_code_userprofile_referrer'),
        ('dashboard', '0005_account_status_account_transaction_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=16, unique=True)),
                ('withdraw_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('withdrawal_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=10)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=16, unique=True)),
                ('withdrawal_date', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile')),
                ('withdrawal_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.withdrawalhistory')),
            ],
        ),
    ]
