# Generated by Django 4.2.3 on 2023-08-02 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_userprofile_referral_code_userprofile_referrer'),
        ('dashboard', '0007_alter_withdrawal_transaction_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransactionHistory',
            new_name='DepositHistory',
        ),
    ]
