# Generated by Django 4.2.3 on 2023-08-03 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_rename_transactionhistory_deposithistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='status',
        ),
        migrations.RemoveField(
            model_name='account',
            name='transaction_date',
        ),
        migrations.RemoveField(
            model_name='account',
            name='transaction_id',
        ),
    ]
